### ISSUE TITLE
[FEATURE REQUEST] - Implement `--recreate-pods`

### ISSUE THREAD

**Issue by sudermanjr** [reactiveops/autohelm#49]
Actually, just implement `--addl-args`

**Comment by ejether** [comment]
Additional args sound be able to pass arbitrary args to the `helm` binary to avoid having to make a new version of autohelm for every new arg in `helm`.

**Comment by ejether** [comment]
More thoughts from Slack:
Nick Huanca [2 minutes ago]
instead of command line flags couldn't that be sourced as a part of the file? `helm_args: []`

EJ Etherington [1 minute ago]
Could do both. I like the idea of the `--additional-args` flag for troubleshooting purposes.  But the same machinery can support `helm_args:` per chart or per `course.yml` pretty easily.

**Comment by ejether** [comment]
All in all, I think we could add a new multiple command line arg `--helm-args`, add a `helm_args` section to the `course.yml` spec and also per chart. As part of that, also deprecate the other command line args that are essentially just `--helm-args` but leaving the ones that require special logic. This would provide more than intended functionality, but also reduce the amount of changes required when new Helm args are released.

**Comment by sudermanjr** [comment]
Just as an additional note: I would be happy to see these implemented as separate PRs since there are essentially now 2 or 3 features coming from this.

**Comment by erkolson** [comment]
`--helm-args` is here:
https://github.com/reactiveops/autohelm/pull/54

I didn't have time to take a look at the `helm_args` part in `course.yml`

**Comment by ejether** [comment]
closing in favor of: https://github.com/reactiveops/autohelm/issues/55
